# Generated by Django 3.0.6 on 2020-06-10 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20200610_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinpayment',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
            preserve_default=False,
        ),
    ]
